[profile.default]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200

test = "forge-test"

libs = [
    "lib",
    "node_modules",
]
remappings = [
    "@solidity-parser/=node_modules/@solidity-parser/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "modules/=src/modules/",
    "contracts/=src/",
    "@pythnetwork/pyth-sdk-solidity/=node_modules/@pythnetwork/pyth-sdk-solidity"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

# Monad Testnet Configuration
eth-rpc-url="https://testnet-rpc.monad.xyz"
chain_id = 10143